export const copy = {
  en: {
    nav: ["Programs", "Results", "Guides", "About"],
    kicker: "COACHING BUILT FOR REAL LIFE",
    title: "Stronger habits. Better body. More energy.",
    text: "Personal coaching, focused group programs and practical guides for busy people who want visible results without extreme routines.",
    start: "Start your transformation",
    stories: "Watch success stories",
    stats: ["clients transformed", "active coaching", "countries", "average rating"],
    methodTitle: "A system that keeps you moving",
    methodText: "Clear structure, regular feedback and realistic progress you can maintain.",
    steps: [
      ["01", "Personal strategy", "Training and nutrition adapted to your schedule, goals and starting point."],
      ["02", "Weekly coaching", "Simple check-ins, form feedback, accountability and plan adjustments."],
      ["03", "Long-term results", "Build habits and strength that continue beyond one short challenge."],
    ],
    programTitle: "Choose the support that fits your goal",
    programText: "Private coaching, small groups, focused programs and self-paced resources.",
    programs: [
      ["1:1 Coaching", "Private coaching", "Personal workouts, nutrition strategy, weekly calls and direct support.", "$299 / month", "Apply now"],
      ["Small Group", "Up to 8 people", "Structured group training, shared accountability and coach feedback.", "$149 / month", "Join the group"],
      ["90-Day Reset", "Cohort program", "A focused transformation flow with weekly milestones and progress reviews.", "$399", "Reserve a place"],
      ["Training Guides", "Self-paced", "Gym, home and mobility guides with video demos and progression plans.", "From $29", "Browse guides"],
    ],
    offer: "LIMITED COHORT OFFER",
    discount: "90-Day Transformation",
    discountText: "Join the next coaching group and save 25% before registration closes.",
    claim: "Claim the discount",
    timer: ["Days", "Hours", "Minutes", "Seconds"],
    resultsTitle: "Proof built on consistency",
    resultsText: "Real clients, practical plans and results created without unsustainable restrictions.",
    before: "Before",
    after: "After",
    storiesData: [
      ["Marta", "-14 kg", "12 weeks", "I finally stopped starting over every Monday."],
      ["Daniel", "+6 kg strength", "16 weeks", "Training became part of my life instead of another failed plan."],
      ["Sofia", "-9 cm waist", "10 weeks", "The structure and feedback made everything easier."],
    ],
    progressTitle: "The process feels different every month",
    progressText: "Your plan evolves as your fitness, recovery and confidence improve.",
    progress: [
      ["Week 1", "Build the rhythm", 25],
      ["Week 5", "Increase capacity", 58],
      ["Week 12", "Own the routine", 100],
    ],
    guidesTitle: "Guides you can actually follow",
    guidesText: "Simple, well-designed plans for the gym, home and everyday nutrition.",
    guides: [
      ["Strong at Home", "8-week home strength guide", "$39"],
      ["Gym Confidence", "Beginner gym progression plan", "$49"],
      ["Protein Made Simple", "Practical nutrition guide", "$19"],
    ],
    aboutTitle: "Coaching without punishment",
    aboutText: "I help people train with structure, eat with more confidence and create routines that fit real schedules. The goal is not perfection—it is a body and lifestyle you can trust.",
    faqTitle: "Questions before you start",
    faqs: [
      ["Do I need gym experience?", "No. Programs are adapted to your current ability and can start from a complete beginner level."],
      ["Is nutrition included?", "Yes, coaching packages include practical nutrition guidance, meal structure and regular adjustments."],
      ["Can I train from home?", "Yes. Home programs can be built around dumbbells, resistance bands or minimal equipment."],
      ["How do group programs work?", "You receive a structured plan, weekly targets, group support and direct feedback from the coach."],
    ],
    sticky: "Ready to move forward?",
    stickyBtn: "Book a free consultation",
    modalTitle: "Tell me about your goal",
    modalText: "Leave your details and I'll recommend the best coaching option.",
    name: "Name",
    email: "Email",
    goal: "Your main goal",
    send: "Send request",
  },
  pl: {
    nav: ["Programy", "Rezultaty", "Poradniki", "O mnie"],
    kicker: "COACHING DOPASOWANY DO PRAWDZIWEGO ŻYCIA",
    title: "Lepsze nawyki. Silniejsze ciało. Więcej energii.",
    text: "Trening personalny, kameralne grupy i praktyczne poradniki dla zapracowanych osób, które chcą widocznych efektów bez skrajnych metod.",
    start: "Rozpocznij przemianę",
    stories: "Zobacz historie klientów",
    stats: ["przemian klientów", "aktywnych podopiecznych", "krajów", "średnia ocena"],
    methodTitle: "System, który pomaga działać regularnie",
    methodText: "Jasna struktura, stały feedback i realistyczny progres, który da się utrzymać.",
    steps: [
      ["01", "Indywidualna strategia", "Trening i odżywianie dopasowane do Twojego grafiku, celu i poziomu."],
      ["02", "Cotygodniowy coaching", "Proste check-iny, korekta techniki, motywacja i aktualizacje planu."],
      ["03", "Długoterminowe efekty", "Budujesz siłę i nawyki, które zostają na dłużej niż jeden challenge."],
    ],
    programTitle: "Wybierz wsparcie dopasowane do celu",
    programText: "Coaching indywidualny, małe grupy, konkretne programy i materiały do pracy samodzielnej.",
    programs: [
      ["Coaching 1:1", "Indywidualna współpraca", "Plan treningowy, strategia żywieniowa, cotygodniowe rozmowy i bezpośrednie wsparcie.", "$299 / miesiąc", "Zgłoś się"],
      ["Mała grupa", "Maksymalnie 8 osób", "Program grupowy, wspólna odpowiedzialność i regularny feedback trenera.", "$149 / miesiąc", "Dołącz do grupy"],
      ["90-dniowy Reset", "Program w edycjach", "Skupiony proces transformacji z tygodniowymi celami i analizą postępów.", "$399", "Zarezerwuj miejsce"],
      ["Poradniki treningowe", "We własnym tempie", "Plany na siłownię, do domu i mobility z filmami oraz progresją.", "Od $29", "Zobacz poradniki"],
    ],
    offer: "LIMITOWANA OFERTA",
    discount: "90-dniowa Transformacja",
    discountText: "Dołącz do kolejnej grupy coachingowej i oszczędź 25% przed zamknięciem zapisów.",
    claim: "Odbierz zniżkę",
    timer: ["Dni", "Godziny", "Minuty", "Sekundy"],
    resultsTitle: "Efekty zbudowane na regularności",
    resultsText: "Prawdziwi klienci, praktyczne plany i rezultaty bez nierealnych ograniczeń.",
    before: "Przed",
    after: "Po",
    storiesData: [
      ["Marta", "-14 kg", "12 tygodni", "W końcu przestałam zaczynać od nowa w każdy poniedziałek."],
      ["Daniel", "+6 kg siły", "16 tygodni", "Trening stał się częścią mojego życia, a nie kolejną porażką."],
      ["Sofia", "-9 cm w talii", "10 tygodni", "Struktura i feedback sprawiły, że wszystko stało się prostsze."],
    ],
    progressTitle: "Proces zmienia się z każdym miesiącem",
    progressText: "Plan rozwija się razem z Twoją formą, regeneracją i pewnością siebie.",
    progress: [
      ["Tydzień 1", "Zbuduj rytm", 25],
      ["Tydzień 5", "Zwiększ możliwości", 58],
      ["Tydzień 12", "Przejmij kontrolę", 100],
    ],
    guidesTitle: "Poradniki, które naprawdę da się stosować",
    guidesText: "Proste plany na siłownię, do domu i do codziennego odżywiania.",
    guides: [
      ["Silna w domu", "8-tygodniowy plan treningowy", "$39"],
      ["Pewność na siłowni", "Plan progresji dla początkujących", "$49"],
      ["Białko bez komplikacji", "Praktyczny poradnik żywieniowy", "$19"],
    ],
    aboutTitle: "Coaching bez karania siebie",
    aboutText: "Pomagam trenować z planem, jeść z większą pewnością i budować rutyny dopasowane do prawdziwego życia. Nie chodzi o perfekcję, tylko o ciało i styl życia, którym możesz zaufać.",
    faqTitle: "Pytania przed startem",
    faqs: [
      ["Czy potrzebuję doświadczenia na siłowni?", "Nie. Program jest dopasowany do Twojego poziomu i może zaczynać się od podstaw."],
      ["Czy plan obejmuje odżywianie?", "Tak. Pakiety coachingowe zawierają praktyczne wskazówki żywieniowe i regularne zmiany."],
      ["Czy mogę trenować w domu?", "Tak. Program może bazować na hantlach, gumach oporowych lub minimalnym sprzęcie."],
      ["Jak działa program grupowy?", "Otrzymujesz plan, cotygodniowe cele, wsparcie grupy i bezpośredni feedback trenera."],
    ],
    sticky: "Gotowa/y ruszyć dalej?",
    stickyBtn: "Umów bezpłatną konsultację",
    modalTitle: "Opowiedz mi o swoim celu",
    modalText: "Zostaw dane, a polecę najlepszą opcję współpracy.",
    name: "Imię",
    email: "Email",
    goal: "Twój główny cel",
    send: "Wyślij zgłoszenie",
  },
  uk: {
    nav: ["Програми", "Результати", "Гайди", "Про мене"],
    kicker: "КОУЧИНГ, ЯКИЙ ПАСУЄ ДО РЕАЛЬНОГО ЖИТТЯ",
    title: "Кращі звички. Сильніше тіло. Більше енергії.",
    text: "Персональний супровід, невеликі групи та практичні гайди для зайнятих людей, які хочуть помітних результатів без крайнощів.",
    start: "Почати трансформацію",
    stories: "Дивитися історії клієнтів",
    stats: ["трансформацій клієнтів", "активних учасників", "країн", "середній рейтинг"],
    methodTitle: "Система, яка допомагає рухатися регулярно",
    methodText: "Чітка структура, постійний зворотний зв'язок і реалістичний прогрес.",
    steps: [
      ["01", "Персональна стратегія", "Тренування та харчування під ваш графік, цілі й стартовий рівень."],
      ["02", "Щотижневий супровід", "Прості звіти, перевірка техніки, підтримка та корекція плану."],
      ["03", "Довготривалий результат", "Звички та сила, які залишаються після завершення програми."],
    ],
    programTitle: "Оберіть формат підтримки під вашу мету",
    programText: "Персональний коучинг, малі групи, окремі потоки та матеріали для самостійної роботи.",
    programs: [
      ["Коучинг 1:1", "Персональний супровід", "Індивідуальні тренування, стратегія харчування, щотижневі дзвінки та пряма підтримка.", "$299 / місяць", "Подати заявку"],
      ["Мала група", "До 8 людей", "Структурована групова програма, спільна відповідальність і зворотний зв'язок тренера.", "$149 / місяць", "Приєднатися"],
      ["90-денний Reset", "Потокова програма", "Сфокусована трансформація з тижневими цілями та перевіркою прогресу.", "$399", "Забронювати місце"],
      ["Тренувальні гайди", "У власному темпі", "Плани для залу, дому та мобільності з відео й системою прогресії.", "Від $29", "Переглянути гайди"],
    ],
    offer: "ОБМЕЖЕНА ПРОПОЗИЦІЯ",
    discount: "90-денна Трансформація",
    discountText: "Приєднуйтеся до наступного потоку та отримайте знижку 25% до завершення реєстрації.",
    claim: "Отримати знижку",
    timer: ["Дні", "Години", "Хвилини", "Секунди"],
    resultsTitle: "Результати, побудовані на регулярності",
    resultsText: "Реальні клієнти, практичні плани та зміни без виснажливих обмежень.",
    before: "До",
    after: "Після",
    storiesData: [
      ["Марта", "-14 кг", "12 тижнів", "Я нарешті перестала починати все заново щопонеділка."],
      ["Даніель", "+6 кг сили", "16 тижнів", "Тренування стали частиною мого життя, а не черговою невдалою спробою."],
      ["Софія", "-9 см у талії", "10 тижнів", "Структура й підтримка зробили процес набагато простішим."],
    ],
    progressTitle: "Процес змінюється щомісяця",
    progressText: "План розвивається разом із вашою формою, відновленням і впевненістю.",
    progress: [
      ["Тиждень 1", "Створити ритм", 25],
      ["Тиждень 5", "Збільшити витривалість", 58],
      ["Тиждень 12", "Закріпити систему", 100],
    ],
    guidesTitle: "Гайди, які реально виконувати",
    guidesText: "Зрозумілі плани для залу, дому та щоденного харчування.",
    guides: [
      ["Сильна вдома", "8-тижневий план домашніх тренувань", "$39"],
      ["Впевненість у залі", "Програма для початківців", "$49"],
      ["Білок без складнощів", "Практичний гайд із харчування", "$19"],
    ],
    aboutTitle: "Коучинг без покарання себе",
    aboutText: "Допомагаю тренуватися структуровано, харчуватися впевненіше та створювати звички, які підходять до реального графіка. Мета — не ідеальність, а тіло й спосіб життя, яким можна довіряти.",
    faqTitle: "Запитання перед стартом",
    faqs: [
      ["Чи потрібен досвід у залі?", "Ні. Програма адаптується до вашого рівня і може починатися з нуля."],
      ["Чи входить харчування?", "Так. Пакети включають практичні рекомендації, структуру прийомів їжі та регулярні корекції."],
      ["Чи можна тренуватися вдома?", "Так. Домашній план може базуватися на гантелях, резинках або мінімальному обладнанні."],
      ["Як працюють групові потоки?", "Ви отримуєте план, щотижневі цілі, підтримку групи та прямий зворотний зв'язок тренера."],
    ],
    sticky: "Готові рухатися далі?",
    stickyBtn: "Записатися на безкоштовну консультацію",
    modalTitle: "Розкажіть про вашу мету",
    modalText: "Залиште контакти, і я пораджу найкращий формат роботи.",
    name: "Ім'я",
    email: "Email",
    goal: "Ваша головна мета",
    send: "Надіслати заявку",
  },
};

export const imgs = [
  ["/transformations/marta-after.png", "/transformations/marta-before.png"],
  ["/transformations/daniel-after.png", "/transformations/daniel-before.png"],
  ["/transformations/sofia-after.png", "/transformations/sofia-before.png"],
];